from pathlib import Path
import sys
import pandas as pd
import numpy as np

from src.driftx.config import CONFIG
from src.driftx.data.preprocessing import load_training_data, create_rul_target


def save_scenario(df, name, change_point, cause, first_stage):
    output = Path("data/interim") / f"{name}.csv"
    result = df.copy()
    result["scenario"] = name
    result["change_point"] = change_point
    result["true_cause"] = cause
    result["true_first_stage"] = first_stage
    result.to_csv(output, index=False)

    print(
        f"{name:<24} | "
        f"cause={cause:<18} | "
        f"first={first_stage:<12} | "
        f"cp={change_point}"
    )


def main(seed=42, change_fraction=0.50, magnitude=0.30):
    raw_dir = Path(CONFIG["paths"]["raw_data"])

    df = create_rul_target(load_training_data(raw_dir))
    df = df.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    n = len(df)
    cp = int(n * change_fraction)

    print("\n=== ROBUSTNESS DRIFT LABORATORY ===")
    print(f"Seed: {seed}")
    print(f"Rows: {n}")
    print(f"Change fraction: {change_fraction:.2f}")
    print(f"Change point: {cp}")
    print(f"Magnitude: {magnitude:.2f}\n")

    # F01: abrupt feature drift
    f01 = df.copy()
    f01.loc[cp:, "sensor_2"] *= 1.0 + magnitude
    save_scenario(
        f01, "F01_feature_abrupt", cp,
        "FEATURE_DRIFT", "feature"
    )

    # F02: gradual feature drift
    f02 = df.copy()
    strength = np.zeros(n)
    strength[cp:] = np.linspace(0.0, magnitude, n - cp)
    f02["sensor_7"] *= 1.0 + strength
    save_scenario(
        f02, "F02_feature_gradual", cp,
        "FEATURE_DRIFT", "feature"
    )

    # F03: multi-feature drift
    f03 = df.copy()
    for feature in ["sensor_2", "sensor_7", "sensor_11"]:
        f03.loc[cp:, feature] *= 1.0 + magnitude
    save_scenario(
        f03, "F03_multi_feature", cp,
        "FEATURE_DRIFT", "feature"
    )

    # F04: concept drift
    f04 = df.copy()
    f04["RUL"] = f04["RUL"].astype(float); original_rul = f04["RUL"].copy()
    f04.loc[cp:, "RUL"] = (
        original_rul.loc[cp:] * (1.0 - magnitude)
        + f04.loc[cp:, "sensor_2"].rank(pct=True) * 10
    )
    f04["concept_drift_active"] = 0
    f04.loc[cp:, "concept_drift_active"] = 1
    save_scenario(
        f04, "F04_concept", cp,
        "CONCEPT_DRIFT", "residual"
    )

    # F05/F06/F07 are generated by generate_prediction_scenarios.py
    # after this laboratory generation.

    # F08: recurrent feature drift
    f08 = df.copy()
    cp2 = int(n * min(change_fraction + 0.25, 0.90))
    f08.loc[cp:, "sensor_2"] *= 1.0 + magnitude
    f08.loc[cp2:, "sensor_2"] /= 1.0 + magnitude
    save_scenario(
        f08, "F08_recurrent", cp,
        "RECURRENT_DRIFT", "feature"
    )

    # F09: no drift
    f09 = df.copy()
    save_scenario(
        f09, "F09_no_drift", None,
        "NO_DRIFT", "none"
    )

    print("\nRobustness scenarios generated successfully.")


if __name__ == "__main__":
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 42
    change_fraction = float(sys.argv[2]) if len(sys.argv) > 2 else 0.50
    magnitude = float(sys.argv[3]) if len(sys.argv) > 3 else 0.30

    main(seed, change_fraction, magnitude)
